sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t patrickstapletonpersonal/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true patrickstapletonpersonal/docker-react npm run test